import { Student } from './attendance.models';

export const MASTER_STUDENTS: Student[] = [
  { name: 'Sovnasruti Jena', registrationNumber: 'REG001' },
  { name: 'Swaaat Das', registrationNumber: 'REG002' },
  { name: 'Samikshya Samadarshini', registrationNumber: 'REG003' },
  { name: 'Archana Devi', registrationNumber: 'REG004' },
  { name: 'Roshan Mishra', registrationNumber: 'REG005' },
  { name: 'Satvabrat Saranq', registrationNumber: 'REG006' },
  { name: 'Privanshu Sekhar', registrationNumber: 'REG007' },
  { name: 'Ankit Prasad', registrationNumber: 'REG008' },
  { name: 'Ronit Kumar Swain', registrationNumber: 'REG009' },
  { name: 'Jagannath Padhi', registrationNumber: 'REG010' },
  { name: 'Rohan Kumar Nayak', registrationNumber: 'REG011' },
  { name: 'Tushar Ranjan Muduli', registrationNumber: 'REG012' },
  { name: 'Snehasis Das', registrationNumber: 'REG013' },
  { name: 'Omkar Sahoo', registrationNumber: 'REG014' },
  { name: 'Motilal Turuk', registrationNumber: 'REG015' },
  { name: 'Gayatri Pati', registrationNumber: 'REG016' },
  { name: 'Gaurav Patra', registrationNumber: 'REG017' },
  { name: 'Avush Guharav', registrationNumber: 'REG018' },
  { name: 'Anuo Mohanty', registrationNumber: 'REG019' },
  { name: 'Adil Khan', registrationNumber: 'REG020' },
  { name: 'Anurao Mohanty', registrationNumber: 'REG021' },
  { name: 'Debashis Tripathy', registrationNumber: 'REG022' },
  { name: 'Safaq Jamal', registrationNumber: 'REG023' },
  { name: 'Sohan Mohanty', registrationNumber: 'REG024' },
  { name: 'Hrusikesh Pattnaik', registrationNumber: 'REG025' },
  { name: 'Chandan Kumar Sahu', registrationNumber: 'REG026' },
  { name: 'Sitikantha Dalal', registrationNumber: 'REG027' },
  { name: 'Titiksha Sahu', registrationNumber: 'REG028' },
  { name: 'Aniali Sahoo', registrationNumber: 'REG029' },
  { name: 'Sushree Sanjita Sethi', registrationNumber: 'REG030' },
  { name: 'Mama Bisoi', registrationNumber: 'REG031' },
  { name: 'Tanmay Sahu', registrationNumber: 'REG032' },
  { name: 'Pratik Parag Pani', registrationNumber: 'REG033' },
  { name: 'Ranit Das', registrationNumber: 'REG034' },
  { name: 'Shobha Kumari', registrationNumber: 'REG035' },
  { name: 'CS Vishal Rout', registrationNumber: 'REG036' },
  { name: 'Rajesh Behera', registrationNumber: 'REG037' },
  { name: 'Maniket Padhan', registrationNumber: 'REG038' },
  { name: 'Jeevan Jyoti Panigrahi', registrationNumber: 'REG039' },
  { name: 'Avush Mishra', registrationNumber: 'REG040' },
  { name: 'Mohit Singal', registrationNumber: 'REG041' },
  { name: 'Dhiraj Mahapatra', registrationNumber: 'REG042' },
  { name: 'Swayam Sahu', registrationNumber: 'REG043' },
  { name: 'Subhashree Mohapatra', registrationNumber: 'REG044' },
  { name: 'Subhalaxmi Sahoo', registrationNumber: 'REG045' },
  { name: 'Rajshree Panda', registrationNumber: 'REG046' },
  { name: 'Soumvashree Panda', registrationNumber: 'REG047' },
  { name: 'Rupali Jena', registrationNumber: 'REG048' },
  { name: 'Lipsa Panda', registrationNumber: 'REG049' },
  { name: 'Shreshtha Mohanty', registrationNumber: 'REG050' },
  { name: 'Sukanva Subhadarshini', registrationNumber: 'REG051' },
  { name: 'Aniali Mishra', registrationNumber: 'REG052' },
  { name: 'Prachi Pratvasha Das', registrationNumber: 'REG053' },
  { name: 'Nirmit Navak', registrationNumber: 'REG054' },
  { name: 'Padmalava Meher', registrationNumber: 'REG055' },
  { name: 'Shubham Kumar', registrationNumber: 'REG056' },
  { name: 'Yash Kumar', registrationNumber: 'REG057' },
  { name: 'Sasawat Rout', registrationNumber: 'REG058' },
  { name: 'Adarsh Kumar', registrationNumber: 'REG059' },
  { name: 'Amit Kumar Yash', registrationNumber: 'REG060' },
  { name: 'C H Tanisha', registrationNumber: 'REG061' },
  { name: 'Pratikshya Acharya', registrationNumber: 'REG062' },
  { name: 'Mahesh Dakua', registrationNumber: 'REG063' },
  { name: 'Anil Kumar Nayak', registrationNumber: 'REG064' },
  { name: 'Khushi Sahu', registrationNumber: 'REG065' }
];
